"""
LEGO provided functions and values.
"""

from collections.abc import Callable
from typing import Iterable, overload
from hub import Image

def clear() -> None: ...
def rotation(rotation: int) -> None: ...
@overload
def align() -> int: ...
@overload
def align(face: int) -> int: ...
@overload
def invert() -> bool: ...
@overload
def invert(invert: bool) -> bool: ...
def callback(callback: Callable[[int], None]) -> None: ...
@overload
def pixel(x: int, y: int) -> int: ...
@overload
def pixel(x: int, y: int, brightness: int) -> None: ...
@overload
def show(text: str) -> None: ...
@overload
def show(number: int) -> None: ...
@overload
def show(image: Image) -> None: ...
@overload
def show(
    image: Iterable[Image],
    delay: int = 400,
    level: int = 9,
    clear: bool = False,
    wait: bool = True,
    loop: bool = False,
    fade: int = 0,
) -> None: ...
